#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QPointer>
#include <QLabel>
#include <mplayerfe.h>
#include <seekview.h>
#include <QQueue>
namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT
    
public:
    QPointer<QLabel> lab;
    QPointer<mplayerfe> fr;
    SeekView *mpseekView;
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();
    
private slots:
    void pauseSeekView();
    void on_pushButton_2_clicked();     //for loading the media file
    void restartSeekView(int ec,bool stop);
    void startingPlaybackframe();
    void showSeekpos(QString pos, QPoint *pt);
    void hideframe();
    void onSliderClick(QString pos, QPoint *pt);

    void on_pushButton_3_clicked();

    void on_pushButton_clicked();     //undo the cut generated by last click on slider

private:

    QString getFilter();
    QQueue<int> time_queue;

    QString currentFile;
    Ui::MainWindow *ui;

};

#endif // MAINWINDOW_H
