#############################################################################
# Makefile for building: slider_testing
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Feb 19 09:22:25 2016
# Project:  ../slider_testing/slider_testing.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../slider_testing/slider_testing.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../slider_testing -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I../slider_testing -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../slider_testing/main.cpp \
		../slider_testing/mainwindow.cpp \
		../slider_testing/rphslider.cpp \
		../slider_testing/seekview.cpp \
		../slider_testing/myprocess.cpp \
		../slider_testing/mplayerfe.cpp \
		../slider_testing/rphfile.cpp moc_mainwindow.cpp \
		moc_rphslider.cpp \
		moc_seekview.cpp \
		moc_myprocess.cpp \
		moc_mplayerfe.cpp \
		qrc_slider_seek.cpp
OBJECTS       = main.o \
		mainwindow.o \
		rphslider.o \
		seekview.o \
		myprocess.o \
		mplayerfe.o \
		rphfile.o \
		moc_mainwindow.o \
		moc_rphslider.o \
		moc_seekview.o \
		moc_myprocess.o \
		moc_mplayerfe.o \
		qrc_slider_seek.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../slider_testing/slider_testing.pro
QMAKE_TARGET  = slider_testing
DESTDIR       = 
TARGET        = slider_testing

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_seekview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../slider_testing/slider_testing.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../slider_testing/slider_testing.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../slider_testing/slider_testing.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/slider_testing1.0.0 || $(MKDIR) .tmp/slider_testing1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/slider_testing1.0.0/ && $(COPY_FILE) --parents ../slider_testing/mainwindow.h ../slider_testing/rphslider.h ../slider_testing/seekview.h ../slider_testing/myprocess.h ../slider_testing/mplayerfe.h ../slider_testing/rphfile.h .tmp/slider_testing1.0.0/ && $(COPY_FILE) --parents ../slider_testing/slider_seek.qrc .tmp/slider_testing1.0.0/ && $(COPY_FILE) --parents ../slider_testing/main.cpp ../slider_testing/mainwindow.cpp ../slider_testing/rphslider.cpp ../slider_testing/seekview.cpp ../slider_testing/myprocess.cpp ../slider_testing/mplayerfe.cpp ../slider_testing/rphfile.cpp .tmp/slider_testing1.0.0/ && $(COPY_FILE) --parents ../slider_testing/mainwindow.ui ../slider_testing/seekview.ui .tmp/slider_testing1.0.0/ && (cd `dirname .tmp/slider_testing1.0.0` && $(TAR) slider_testing1.0.0.tar slider_testing1.0.0 && $(COMPRESS) slider_testing1.0.0.tar) && $(MOVE) `dirname .tmp/slider_testing1.0.0`/slider_testing1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/slider_testing1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_rphslider.cpp moc_seekview.cpp moc_myprocess.cpp moc_mplayerfe.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_rphslider.cpp moc_seekview.cpp moc_myprocess.cpp moc_mplayerfe.cpp
moc_mainwindow.cpp: ../slider_testing/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../slider_testing/mainwindow.h -o moc_mainwindow.cpp

moc_rphslider.cpp: ../slider_testing/rphslider.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../slider_testing/rphslider.h -o moc_rphslider.cpp

moc_seekview.cpp: ../slider_testing/seekview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../slider_testing/seekview.h -o moc_seekview.cpp

moc_myprocess.cpp: ../slider_testing/myprocess.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../slider_testing/myprocess.h -o moc_myprocess.cpp

moc_mplayerfe.cpp: ../slider_testing/winampdspdialog.h \
		../slider_testing/fontloaddialog.h \
		../slider_testing/myprocess.h \
		../slider_testing/assstyles.h \
		../slider_testing/mplayerfe.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../slider_testing/mplayerfe.h -o moc_mplayerfe.cpp

compiler_rcc_make_all: qrc_slider_seek.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_slider_seek.cpp
qrc_slider_seek.cpp: ../slider_testing/slider_seek.qrc \
		../slider_testing/images/seekview.png
	/usr/bin/rcc -name slider_seek ../slider_testing/slider_seek.qrc -o qrc_slider_seek.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_seekview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_seekview.h
ui_mainwindow.h: ../slider_testing/mainwindow.ui \
		../slider_testing/rphslider.h
	/usr/bin/uic-qt4 ../slider_testing/mainwindow.ui -o ui_mainwindow.h

ui_seekview.h: ../slider_testing/seekview.ui
	/usr/bin/uic-qt4 ../slider_testing/seekview.ui -o ui_seekview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: ../slider_testing/main.cpp ../slider_testing/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../slider_testing/main.cpp

mainwindow.o: ../slider_testing/mainwindow.cpp ../slider_testing/mainwindow.h \
		ui_mainwindow.h \
		../slider_testing/rphslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../slider_testing/mainwindow.cpp

rphslider.o: ../slider_testing/rphslider.cpp ../slider_testing/rphslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rphslider.o ../slider_testing/rphslider.cpp

seekview.o: ../slider_testing/seekview.cpp ../slider_testing/seekview.h \
		ui_seekview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seekview.o ../slider_testing/seekview.cpp

myprocess.o: ../slider_testing/myprocess.cpp ../slider_testing/myprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myprocess.o ../slider_testing/myprocess.cpp

mplayerfe.o: ../slider_testing/mplayerfe.cpp ../slider_testing/mplayerfe.h \
		../slider_testing/winampdspdialog.h \
		../slider_testing/fontloaddialog.h \
		../slider_testing/myprocess.h \
		../slider_testing/assstyles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mplayerfe.o ../slider_testing/mplayerfe.cpp

rphfile.o: ../slider_testing/rphfile.cpp ../slider_testing/rphfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rphfile.o ../slider_testing/rphfile.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_rphslider.o: moc_rphslider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rphslider.o moc_rphslider.cpp

moc_seekview.o: moc_seekview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seekview.o moc_seekview.cpp

moc_myprocess.o: moc_myprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myprocess.o moc_myprocess.cpp

moc_mplayerfe.o: moc_mplayerfe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mplayerfe.o moc_mplayerfe.cpp

qrc_slider_seek.o: qrc_slider_seek.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_slider_seek.o qrc_slider_seek.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

